language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_8fdff2d88322_key -iv $encrypted_8fdff2d88322_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 66.42.94.70\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config